# Configure how the simulator will work
args:
  # Simulation preset. One of:
  # - GiuliaStd: Standard simulation
  # - GiuliaMfl': Multi-frequency layer simulation
  preset: 'GiuliaStd'
  # Simulation model. One of:
  # ITU_R_M2135_UMa, ITU_R_M2135_UMi, 3GPPTR36_814_Case_1,  3GPPTR36_814_Case_1_omni, 3GPPTR36_814_Case_1_single_bs,
  # 3GPPTR36_814_Case_1_single_bs_omni, 3GPPTR36_814_Case_1_omni_dana,  3GPPTR38_901_UMa_C1, 3GPPTR38_901_UMa_C2,
  # 3GPPTR38_901_UMa_lsc, 3GPPTR38_901_UMa_lsc_sn, 3GPPTR38_901_UMa_lsc_single_bs, 3GPPTR38_901_UMa_lsc_single_sector,
  # 3GPPTR38_901_UMa_2GHz_lsc, 3GPPTR38_901_UMa_C_band_lsc, 3GPPTR38_901_UMi_C1, 3GPPTR38_901_UMi_C2, 3GPPTR38_901_UMi_lsc,
  # 3GPPTR38_901_UMi_C_band_lsc, 3GPPTR38_901_UMi_fr3_lsc, 3GPPTR38_901_UPi_fr3_lsc, 3GPPTR36_777_UMa_AV, 3GPPTR36_777_UMi_AV,
  # 3GPPTR38_811_Urban_NTN, 3GPPTR38_811_Dense_Urban_NTN, 3GPPTR38_811_Dense_Urban_HAPS_ULA, 3GPPTR38_811_Dense_Urban_HAPS_UPA,
  # 3GPPTR38_811_Dense_Urban_HAPS_Reflector, ITU_R_M2135_UMa_multilayer, ITU_R_M2135_UMa_Umi_colocated_multilayer,
  # ITU_R_M2135_UMa_Umi_noncolocated_multilayer, 3GPPTR38_901_4G, 3GPPTR38_901_5G, 3GPPTR38_901_6G, 3GPPTR38_901_4G5G_multilayer,
  # 3GPPTR38_901_4G_5G_multilayer, 3GPPTR38_901_4G_5G6G_multilayer, 3GPPTR38_901_4G_5G_6G_multilayer, 3GPPTR38_901_4G5G_cell_reselection,
  # dataset
  scenario_model: 'ITU_R_M2135_UMa'
  # Every ITU and 3GPP scenario model above has its corresponding UE playground deployment model. If we want to use such
  # corresponding model, no need to specify any input. Alternatively, we have other UE playground deployment models.
  # One of:
  # - None (empty/null, default scenario-based)
  # - rectangular
  # - circular
  ue_playground_model:
  # UE distribution model. One of: grid, uniform, uniform_with_hotspots, inhomogeneous_per_cell
  ue_distribution: 'uniform'
  # UE mobility model. One of: None (empty/null), straight_walk, circular_walk
  ue_mobility:
  # Link direction. One of: downlink, uplink, downlink_uplink (both)
  link_direction: 'downlink'
  # Enable wraparound for network topology. true/false
  wraparound:
  # Number of simulation snapshots. A number greater than 0
  snapshots: 2
  # Specify whether you want to enable GPU usage or not. true/false
  enable_GPU: true
  # Enable regression testing mode. true/false
  regression: false
  # Set the logging level. A number between 0 and 4, both inclusive.
  log_level: 0
  # Whether to save the simulation results. 0=false, 1=true
  save_results: 1
  # Generate plots for simulation results. true/false
  plots: false

run:
  # Which example file to run.
  # Options: EV, EV_batch, EV_EE_UEassociation, EV_EE_UEassociation_batch, EV_HapsSym_Reflector
  example: EV

output:
  # The directory where all the output files will be placed. Absolute, or relative to the root of the repository.
  directory: outputs/outputs
  # Which compression method to use for the output data.
  # This is necessary in some cases, because Parquet works with a folder structure, which may be inconvenient to share
  # in some cases. Compressing it helps to move it around.
  # Options: none, zip
  compression: none
  # Will only be considered if `compression` is not "none".
  # If `true`, the original files will be removed after compressing the parquet file structure.
  rm_uncompressed: true
  # All the fields to be included in the output. If empty or not specified all of them will be exported.
  fields:
    - best_serving_cell_ID_per_ue_based_on_CRS
    - best_serving_CRS_coupling_gain_dB
    - best_serving_CRS_distance_3d_m
    - best_serving_CRS_re_noise_per_ue_dBm
    - best_serving_CRS_rsrp_per_ue_dBm
    - best_serving_cell_ID_per_ue_based_on_SSB
    - best_serving_SSB_per_ue
    - best_serving_SSB_coupling_gain_dB
    - best_serving_SSB_distance_3d_m
    - best_serving_SSB_re_noise_per_ue_dBm
    - best_serving_SSB_rsrp_per_ue_dBm
    - best_serving_CSI_RS_per_ue
    - best_serving_CSI_RS_rsrp_per_ue_dBm
    - carrier_throughput_Mbps
    - cell_activity_per_ue
    - cell_throughput_Mbps
    - CRS_interfPower_ue_dBm
    - CRS_RSRP_no_fast_fading_ue_to_cell_dBm
    - CRS_sinr_ue_to_cell_dB
    - CRS_usefulPower_ue_dBm
    - CSI_RS_beam_activity_per_ue
    - CSI_RS_interfPower_ue_dBm
    - CSI_RS_usefulPower_ue_dBm
    - effective_CSI_RS_sinr_ue_to_cell_dB
    - network_power_consumption_kW
    - SSB_beam_activity_per_ue
    - SSB_interfPower_ue_dBm
    - SSB_RSRP_no_fast_fading_ue_to_cell_dBm
    - SSB_sinr_ue_to_cell_dB
    - SSB_usefulPower_ue_dBm
    - ues_per_cell_based_on_CRS
    - ues_per_cell
    - ues_per_CSI_RS_beam
    - ues_per_SSB_beam
    - ue_throughput_based_on_eff_CSI_RS_SINR_per_PRB_Mbps
    - ue_throughput_based_on_ins_CSI_RS_SINR_per_PRB_Mbps
    - ue_throughput_per_carrier_Mbps
